CREATE TABLE "PROTOKOLLIERTER_ZUGRIFF"
(
    "INTERNALID"       INTEGER,
    "AKTIVIERUNG_TS"   TIMESTAMP,
    "DEAKTIVIERUNG_TS" TIMESTAMP,
    "AKTID"            NUMBER,
    "KENNUNG"          VARCHAR2(100 CHAR),
    "TEXT"             VARCHAR2(100 CHAR),
    "AKTIV"            CHAR(1 BYTE),
    CONSTRAINT "PK_PROTOKOLLIERTERZUGRIFF" PRIMARY KEY ("INTERNALID")
);

CREATE SEQUENCE ZUGRIFF_PK_SEQUENCE
    MINVALUE 1
    START WITH 50
    INCREMENT BY 50;
